import axios from "axios";
import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import { jsPDF } from "jspdf";
import { useNavigate } from "react-router-dom";

export default function MorePatientDetails() {
  const [medicalHistories, setMedicalHistories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showMedicalHistories, setShowMedicalHistories] = useState(false);
  const navigate = useNavigate();
  const location = useLocation();
  const { regnum, patientDetails } = location.state;

  // get medical histories for the patient
  useEffect(() => {
    if (regnum) {
      axios
        .get(`http://localhost:8080/medicalhis/medical-history-user/${regnum}`)
        .then((response) => {
          setMedicalHistories(response.data);
          setLoading(false);
        })
        .catch((error) => {
          console.error("Error fetching medical histories:", error);
          setLoading(false);
        });
    }
  }, [regnum]);

  const handleDownloadPrescription = (
    regNo,
    bloodPressure,
    weight,
    temperature,
    diagnosis,
    visitDate,
    prescription
  ) => {
    const doc = new jsPDF();

    doc.setFontSize(16);
    doc.text(`Prescription for Registration No: ${regNo}`, 10, 15);
    doc.setFontSize(12);
    doc.text(`Blood Pressure: ${bloodPressure}`, 10, 25);
    doc.text(`Weight: ${weight}`, 10, 35);
    doc.text(`Temperature: ${temperature}`, 10, 45);
    doc.text(`Diagnosis: ${diagnosis}`, 10, 55);
    doc.text(`Visit Date: ${new Date(visitDate).toLocaleDateString()}`, 10, 65);
    doc.text("Prescription:", 10, 75);
    const splitText = doc.splitTextToSize(prescription, 180);
    doc.text(splitText, 10, 85);
    doc.setFontSize(10);
    doc.text(
      "Generated by Healthcare System",
      10,
      doc.internal.pageSize.height - 10
    );

    const formattedBP = bloodPressure.replace(/\//g, "-");
    doc.save(`Prescription_${regNo}_BP-${formattedBP}_${visitDate}.pdf`);
  };

  // medical history toggling
  const toggleMedicalHistories = () => {
    setShowMedicalHistories(!showMedicalHistories);
  };

  return (
    <>
      <div className="min-h-screen flex flex-col md:flex-row bg-gradient-to-r from-blue-50 to-blue-100">
        <div className="w-full md:w-1/4 bg-gradient-to-r from-[#4A0033] via-[#670047] to-[#9A006C] p-4 md:p-8 flex flex-col justify-between shadow-lg">
          <div className="text-center md:text-left">
            <h1 className="text-xl md:text-2xl font-bold text-white">
              Medical Center University of Vavuniya
            </h1>
            <p className="text-sm text-white mt-2">
              Secure and Reliable Healthcare Services
            </p>
          </div>

          <div className="mt-6 md:mt-0">
            <button
              onClick={() => navigate("/admindashboard")}
              className="w-full bg-white text-blue-600 py-2 px-4 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
            >
              Back to Dashboard
            </button>
          </div>
        </div>

        <div className="w-full md:w-3/4 p-4 md:p-8 flex flex-col items-center">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-4xl p-4 md:p-8">
            <h2 className="text-2xl md:text-4xl font-extrabold text-gray-800 mb-6 text-center md:text-left">
              {patientDetails.fullname} Details
            </h2>

            <div className="flex flex-col md:flex-row gap-6 items-center md:items-start">
              <div className="flex-shrink-0">
                <img
                  src={
                    patientDetails.gender?.toLowerCase() === "female"
                      ? "images/women.png"
                      : "images/man.png"
                  }
                  alt="Patient"
                  className="w-56 h-56 md:w-72 md:h-72 rounded-lg border-4 border-blue-300 shadow-xl hover:scale-105 transition-transform"
                />
              </div>

              <div className="flex-1 space-y-2 text-gray-700 text-sm md:text-lg">
                <p><strong>Registration Number:</strong> {patientDetails.regnum}</p>
                <p><strong>Full Name:</strong> {patientDetails.fullname}</p>
                <p><strong>Address:</strong> {patientDetails.address}</p>
                <p><strong>City:</strong> {patientDetails.city}</p>
                <p><strong>Course:</strong> {patientDetails.course}</p>
                <p><strong>Department:</strong> {patientDetails.department}</p>
                <p><strong>Faculty:</strong> {patientDetails.faculty}</p>
                <p><strong>Blood Group:</strong> {patientDetails.bloodgroup}</p>
                <p><strong>Gender:</strong> {patientDetails.gender}</p>
                <p><strong>Created At:</strong> {new Date(patientDetails.createdAt).toLocaleString()}</p>
                <p><strong>Updated At:</strong> {new Date(patientDetails.updatedAt).toLocaleString()}</p>
              </div>
            </div>
          </div>

          {/* medical history */}
          <div className="w-full max-w-6xl mt-8">
            <button
              onClick={toggleMedicalHistories}
              className="bg-teal-600 text-white px-6 py-2 rounded-lg hover:bg-teal-700 transition-all mb-4"
            >
              {showMedicalHistories ? "Hide Medical Histories" : "View Medical Histories"}
            </button>

            {showMedicalHistories && (
              <>
                {loading ? (
                  <p className="text-gray-600">Loading medical histories...</p>
                ) : medicalHistories.length === 0 ? (
                  <p className="text-gray-600">No medical histories found.</p>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="min-w-full bg-white rounded-lg shadow-md">
                      <thead className="bg-teal-500 text-white">
                        <tr>
                          <th className="px-4 py-2">BP</th>
                          <th className="px-4 py-2">Weight</th>
                          <th className="px-4 py-2">Temp</th>
                          <th className="px-4 py-2">Diagnosis</th>
                          <th className="px-4 py-2">Prescription</th>
                          <th className="px-4 py-2">Date</th>
                          <th className="px-4 py-2">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        {medicalHistories.map((history, index) => (
                          <tr key={index} className="border-b hover:bg-gray-50">
                            <td className="px-4 py-2">{history.bloodPressure}</td>
                            <td className="px-4 py-2">{history.weight}</td>
                            <td className="px-4 py-2">{history.temperature}</td>
                            <td className="px-4 py-2">{history.diagnosis}</td>
                            <td className="px-4 py-2">{history.prescription}</td>
                            <td className="px-4 py-2">
                              {new Date(history.visitDate).toLocaleDateString()}
                            </td>
                            <td className="px-4 py-2">
                              <button
                                onClick={() =>
                                  handleDownloadPrescription(
                                    history.regNo,
                                    history.bloodPressure,
                                    history.weight,
                                    history.temperature,
                                    history.diagnosis,
                                    history.visitDate,
                                    history.prescription
                                  )
                                }
                                className="bg-teal-600 text-white px-3 py-1 rounded hover:bg-teal-700 text-sm"
                              >
                                Download
                              </button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      </div>
    </>
  );
}