import { useEffect, useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { jsPDF } from "jspdf";

export default function PatientDashboard({ regnum }) {
  const navigate = useNavigate();

  const navigatechangepassword = () => navigate("/changepassword");

  const navigateMedicalForm = () => {
    navigate("/submit-medical", {
      state: {
        regnum: patientTemp?.regnum,
        fullname: patientTemp?.fullname,
        email: patientTemp?.email,
      },
    });
  };

  const [patient, setPatientDetails] = useState(null);
  const [patientTemp, setPatientDetailsTemp] = useState(null);
  const [medicalHistories, setMedicalHistories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showMedicalHistories, setShowMedicalHistories] = useState(false);

  // get patient details
  useEffect(() => {
    axios
      .get(`http://localhost:8080/patient/patientdetails/${regnum}`)
      .then((response) => {
        if (response.data.success) setPatientDetails(response.data.patdet);
      })
      .catch((error) => console.error(error));
  }, [regnum]);

  // get patient details to the medical form
  useEffect(() => {
    const fetchPatientDetails = async () => {
      try {
        const response = await axios.get(
          `http://localhost:8080/patient/patientdetails/${regnum}`
        );
        if (response.data.success) setPatientDetailsTemp(response.data.patdet);
      } catch (error) {
        console.error(error);
      }
    };
    if (regnum) fetchPatientDetails();
  }, [regnum]);

  const handleAppointmentClick = () => {
    navigate("/AddAppointment", {
      state: {
        regnum: patientTemp?.regnum,
        fullname: patientTemp?.fullname,
        email: patientTemp?.email,
      },
    });
  };

  const goPatientForms = () => {
    if (!patient) return;
    navigate("/medicalFormsPatient", {
      state: { regnum: patient.regnum },
    });
  };

  // get medical histories
  useEffect(() => {
    if (regnum) {
      axios
        .get(`http://localhost:8080/medicalhis/medical-history-user/${regnum}`)
        .then((res) => {
          setMedicalHistories(res.data);
          setLoading(false);
        })
        .catch((err) => {
          console.error(err);
          setLoading(false);
        });
    }
  }, [regnum]);

  const handleDownloadPrescription = (
    regNo,
    bloodPressure,
    weight,
    temperature,
    diagnosis,
    visitDate,
    prescription
  ) => {
    try {
      const doc = new jsPDF();
      doc.setFontSize(16);
      doc.text(`Prescription for Registration No: ${regNo}`, 10, 15);
      
      doc.setFontSize(12);
      doc.text(`Blood Pressure: ${bloodPressure || "N/A"}`, 10, 25);
      doc.text(`Weight: ${weight}`, 10, 35);
      doc.text(`Temperature: ${temperature}`, 10, 45);
      doc.text(`Diagnosis: ${diagnosis}`, 10, 55);
      doc.text(`Visit Date: ${new Date(visitDate).toLocaleDateString()}`, 10, 65);
      
      doc.text("Prescription:", 10, 75);
      doc.text(doc.splitTextToSize(prescription || "No prescription provided", 180), 10, 85);
      
      doc.setFontSize(10);
      doc.text("Generated by Healthcare System", 10, doc.internal.pageSize.height - 10);
      
      doc.save(`Prescription_${regNo}_${visitDate}.pdf`);
    } catch (error) {
      console.error("PDF Generation Error:", error);
    }
  };

  const toggleMedicalHistories = () => setShowMedicalHistories(!showMedicalHistories);

  return (
    <div className="min-h-screen flex flex-col md:flex-row bg-gradient-to-r from-blue-50 to-purple-50">
      <div className="w-full md:w-1/4 bg-gradient-to-r from-[#4A0033] via-[#670047] to-[#9A006C] p-6 md:p-8 flex flex-col justify-between">
        <div>
          <h1 className="text-xl md:text-2xl font-bold text-white">
            Medical Center University of Vavuniya
          </h1>
          <p className="text-sm md:text-base text-white mt-2">
            Secure and Reliable Healthcare Services
          </p>
        </div>
        <div className="mt-4 md:mt-0">
          <button
            onClick={() => navigate("/")}
            className="w-full bg-white text-blue-600 py-2 px-4 rounded-lg hover:bg-gray-100 transition-all"
          >
            Back to home
          </button>
        </div>
      </div>

      <div className="w-full md:w-3/4 p-4 md:p-8">
        <div className="mb-6">
          <h1 className="text-xl md:text-2xl font-bold text-gray-800">
            Welcome {patient ? `${patient.fullname}'s Dashboard` : "Loading..."}
          </h1>
          <hr className="mt-2 border-t-2 border-gray-200" />
        </div>

        <div className="bg-white p-4 md:p-6 rounded-lg shadow-md mb-6">
          <h2 className="text-lg md:text-xl font-bold text-gray-800">
            Registration Number: <span className="text-blue-600">{regnum}</span>
          </h2>
        </div>

        {patient && (
          <div className="flex flex-col md:flex-row space-y-6 md:space-y-0 md:space-x-6">
            <div className="flex-shrink-0 w-full md:w-1/4">
              <img
                src={
                  patient.gender?.toLowerCase() === "female"
                    ? "images/women.png"
                    : "images/man.png"
                }
                alt="Patients"
                className="w-full h-60 md:h-80 object-cover rounded-lg border-4 border-blue-500"
              />
            </div>
            <div className="flex-1 space-y-2 text-gray-700">
              <p><strong>Full Name:</strong> {patient.fullname}</p>
              <p><strong>Address:</strong> {patient.address}</p>
              <p><strong>City:</strong> {patient.city}</p>
              <p><strong>Course:</strong> {patient.course}</p>
              <p><strong>Department:</strong> {patient.department}</p>
              <p><strong>Faculty:</strong> {patient.faculty}</p>
              <p><strong>Blood Group:</strong> {patient.bloodgroup}</p>
              <p><strong>Gender:</strong> {patient.gender}</p>
              <p><strong>Account Created:</strong> {patient.createdAt}</p>
            </div>
          </div>
        )}

        <div className="flex flex-col sm:flex-row flex-wrap gap-2 mt-6">
          <button onClick={toggleMedicalHistories} className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-all">
            {showMedicalHistories ? "Hide Medical Histories" : "View Medical Histories"}
          </button>
          <button onClick={navigatechangepassword} className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-all">
            Change Password
          </button>
          <button onClick={handleAppointmentClick} className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-all">
            Add Appointment
          </button>
          <button onClick={navigateMedicalForm} className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-all">
            Submit Medical Form
          </button>
          <button
            onClick={goPatientForms}
            className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700"
          >
            Check Approval
          </button>
        </div>

        {/* medical history Table */}
        {showMedicalHistories && (
          <div className="mt-6 overflow-x-auto">
            {loading ? (
              <p className="text-gray-600">Loading medical histories...</p>
            ) : medicalHistories.length === 0 ? (
              <p className="text-gray-600">No medical histories found.</p>
            ) : (
              <table className="min-w-full bg-white rounded-lg shadow-md overflow-hidden">
                <thead>
                  <tr className="bg-teal-500 text-white text-sm">
                    <th className="px-4 py-2 text-left">BP</th>
                    <th className="px-4 py-2 text-left">Weight</th>
                    <th className="px-4 py-2 text-left">Temp</th>
                    <th className="px-4 py-2 text-left">Diagnosis</th>
                    <th className="px-4 py-2 text-left">Prescription</th>
                    <th className="px-4 py-2 text-left">Visit Date</th>
                    <th className="px-4 py-2 text-left">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {medicalHistories.map((history, idx) => (
                    <tr key={idx} className="border-b border-gray-300 hover:bg-gray-50 text-sm">
                      <td className="px-4 py-2">{history.bloodPressure}</td>
                      <td className="px-4 py-2">{history.weight}</td>
                      <td className="px-4 py-2">{history.temperature}</td>
                      <td className="px-4 py-2">{history.diagnosis}</td>
                      <td className="px-4 py-2">{history.prescription}</td>
                      <td className="px-4 py-2">{new Date(history.visitDate).toLocaleDateString()}</td>
                      <td className="px-4 py-2">
                        <button
                          onClick={() =>
                            handleDownloadPrescription(
                              history.regNo,
                              history.bloodPressure, // Corrected order
                              history.weight,
                              history.temperature,
                              history.diagnosis,
                              history.visitDate,
                              history.prescription
                            )
                          }
                          className="bg-teal-600 text-white px-2 py-1 rounded hover:bg-teal-700 text-xs"
                        >
                          Download
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        )}
      </div>
    </div>
  );
}